version: "3.8"
services:
  web:
    image: nginx:alpine  # Lightweight Nginx
    ports:
      - "8080:80"       # Host:Container port mapping
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html  # Mount your HTML
    restart: unless-stopped